import {
  createGlobalTheme,
  createGlobalThemeContract,
} from "@vanilla-extract/css";

export const vars = createGlobalThemeContract({
  color: {
    black: null,
    white: null,
    gray100: null,
    gray200: null,
    gray300: null,
    gray400: null,
    gray500: null,
    gray600: null,
    gray700: null,
    gray800: null,
    gray900: null,
    red: null,
    primary: null,
    bg: null,
    border: null,
    textPrimary: null,
    textSecondary: null,
    textTertiary: null,
  },
  font: {
    body: null,
  },
  space: {
    xs: null,
    sm: null,
    md: null,
    lg: null,
    xl: null,
    xxl: null,
  },
  radius: {
    sm: null,
    md: null,
    lg: null,
    full: null,
  },
  headerHeight: null,
  tabHeight: null,
  maxWidth: null,
});

createGlobalTheme(":root", vars, {
  color: {
    black: "#000000",
    white: "#FFFFFF",
    gray100: "#F5F5F5",
    gray200: "#EEEEEE",
    gray300: "#E0E0E0",
    gray400: "#BDBDBD",
    gray500: "#9E9E9E",
    gray600: "#757575",
    gray700: "#616161",
    gray800: "#424242",
    gray900: "#212121",
    red: "#FF0000",
    primary: "#000000",
    bg: "#FFFFFF",
    border: "#EEEEEE",
    textPrimary: "#000000",
    textSecondary: "#616161",
    textTertiary: "#9E9E9E",
  },
  font: {
    body: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif',
  },
  space: {
    xs: "4px",
    sm: "8px",
    md: "16px",
    lg: "24px",
    xl: "32px",
    xxl: "48px",
  },
  radius: {
    sm: "4px",
    md: "8px",
    lg: "12px",
    full: "9999px",
  },
  headerHeight: "56px",
  tabHeight: "44px",
  maxWidth: "640px",
});
